### ISSUE TITLE
MLF Date-A-Scientist Grade Summary

### ISSUE THREAD

**Issue by mackenzieyoung** [pmcphilwalsh/date-a-scientist#5]
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Great job, your code runs without any errors.
 
### Criteria 2: Exploration of Data
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Very good, the data is explored significantly, and the experimental questions chosen are logical and based on the data exploration. The features chosen to answer the question make sense. Especially good use of reusable functions!
 
### Criteria 3: Machine Learning Techniques used correctly
* _Score Level:_ 3 (Meets expectations)
* _Comment(s):_ In general, your algorithms are used correctly and the correct conclusions are drawn from the results. However, you should not optimize parameters such as random_state and train/test set.
 
### Criteria 4: Report: Are conclusions clear and supported by data?
* _Score Level:_ 2 (Approaches expectations)
* _Comment(s):_ Questions are stated clearly, but your explanations of how the algorithms work are missing. Some conclusions are stated, but evidence is not cited (e.g. saying "Results were _______" without explaining why). Also, it's best to not include your code in your presentation, because it's difficult to read code. It's better to include the plots and explanations of what they're showing and what you can conclude from them.

### Criteria 5: Code formatting
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Very nice job formatting your code into sections and using comments!
 
### Overall Score: 17/20
Nice job overall. Your code was well-formatted and easy to read, and you did a good job exploring the data and features. Great use of custom functions. Your main problem was that you tried to optimize the random state and train/test sets, which is considered to be bad practice (see issue for further explanation). Also, in your presentation, there was too much code and too little explanation of your algorithms and results.

**Comment by pmcphilwalsh** [comment]
Thank you for the feedback!  I agree with all of them.  Is this considered a passing grade or are you expecting me to re work the conclusions and resubmit my project?

**Comment by mackenzieyoung** [comment]
No need to resubmit!

**Comment by pmcphilwalsh** [comment]
tx:)
